#ifndef LUCE_HEADER_CONFIGURATION_STANDARD_NOT_SUPPORTED_HH
#define LUCE_HEADER_CONFIGURATION_STANDARD_NOT_SUPPORTED_HH
#include <Luce/Configuration/Basic-Value.hh>

#ifdef LUCE_CONFIG_COMPILER
#error The standard configuration is invalid.
#endif

#define LUCE_CONFIG_STANDARD LUCE_CONFIG_NOT_SUPPORTED

#define LUCE_MACRO_NO_EXCEPTION LUCE_CONFIG_UNDEFINED

#endif