#ifndef CLUCE_HEADER_CONFIGURATION_LINKINGMODE_VALUE_H
#define CLUCE_HEADER_CONFIGURATION_LINKINGMODE_VALUE_H

#define CLUCE_CONFIG_STATIC (1000012L)
#define CLUCE_CONFIG_SHARED (1000022L)
#define CLUCE_CONFIG_DYNAMIC CLUCE_CONFIG_SHARED

#endif