#ifndef LUCE_HEADER_AI_CONFIGURATION_COMPUTEBYCPU_VALUE_HH
#define LUCE_HEADER_AI_CONFIGURATION_COMPUTEBYCPU_VALUE_HH

#define LUCE_CONFIG_AI_BASIC (1000015L)
#define LUCE_CONFIG_AI_TBB (1000025L)
#define LUCE_CONFIG_AI_OMP (1000035L)

#endif