#ifndef LUCE_HEADER_CONFIGURATION_BASIC_VALUE_HH
#define LUCE_HEADER_CONFIGURATION_BASIC_VALUE_HH

#define LUCE_CONFIG_UNDEFINED (1000010L)

#define LUCE_MACRO_IS_UNDEFINED(configuration) (configuration == LUCE_CONFIG_UNDEFINED)

#endif