#ifndef LUCE_HEADER_CONFIGURATION_COMPILER_VALUE_HH
#define LUCE_HEADER_CONFIGURATION_COMPILER_VALUE_HH

#define LUCE_MACRO_MSVC (1993020L)
#define LUCE_MACRO_GCC (1987050L)
#define LUCE_MACRO_CLANG (2007090L)

#endif