#ifndef LUCE_HEADER_CONFIGURATION_LANGUAGE_VALUE_HH
#define LUCE_HEADER_CONFIGURATION_LANGUAGE_VALUE_HH

// English
#define LUCE_CONFIG_ENGLISH (1000012L)
// ÇÑ±¹¾î
#define LUCE_CONFIG_KOREAN (1000022L)

#endif