#ifndef LUCE_HEADER_CONFIGURATION_LINKINGMODE_VALUE_HH
#define LUCE_HEADER_CONFIGURATION_LINKINGMODE_VALUE_HH

#define LUCE_CONFIG_STATIC (1000012L)
#define LUCE_CONFIG_DYNAMIC (1000022L)
#define LUCE_CONFIG_SHARED (1000032L)

#endif