#ifndef LUCE_HEADER_CONFIGURATION_FEATURE_CONSTEXPR_HH
#define LUCE_HEADER_CONFIGURATION_FEATURE_CONSTEXPR_HH
#include <Luce/Configuration/Basic-Value.hh>

#if LUCE_MACRO_IS_YES(LUCE_CONFIG_CONSTEXPR) 
#define LUCE_MACRO_CONSTEXPR constexpr
#else
#define LUCE_MACRO_CONSTEXPR
#endif

#endif