#ifndef LUCE_HEADER_PREPROCESSOR_CONFIGURATION_INTEGERSIZE_VALUE_HH
#define LUCE_HEADER_PREPROCESSOR_CONFIGURATION_INTEGERSIZE_VALUE_HH

#define LUCE_CONFIG_PP_1B (1000016L)
#define LUCE_CONFIG_PP_2B (1000026L)

#endif