#include <Luce/Configuration.hh>

#if LUCE_MACRO_IS_WINDOWS
#include <Windows.h>

#ifdef _WIN32_WINNT_WINXP
#define LUCE_MACRO_I_WINXP _WIN32_WINNT_WINXP
#else
#define LUCE_MACRO_I_WINXP 0x0501
#endif

LUCE_MACRO_STATIC_ASSERT(WINVER >= LUCE_MACRO_I_WINXP,
						 LUCE_LANG_STATICASSERT_WINXP);
#endif