build: Assertion-Common.o Assertion-Windows.o

Assertion-Common.o:
	$(COMPILER) $(COMPILER_FLAG) -o Assertion-Common.o Assertion-Common.cc
	
Assertion-Windows.o:
	$(COMPILER) $(COMPILER_FLAG) -o ../Temporay/Assertion-Windows.o Assertion-Windows.cc